const fs = require('fs');
const path = require('path');
const folder = path.join(__dirname, '..', 'dist');
const index = path.join(folder, 'index.html');
let html = fs.readFileSync(index, 'utf8');
html = html.replace('</head>', '<meta name="description" content="Free classroom cold calling, thinking time and participation tools for teachers."><link rel="stylesheet" href="./website.css"><script src="./site-config.js" defer></script><script src="./website.js" defer></script></head>');
html = html.replace('<div id="root">', fs.readFileSync(path.join(__dirname, '../public/topbar.html'), 'utf8') + '<div id="root">');
html = html.replaceAll('src="/_expo/', 'src="./_expo/').replaceAll('href="/_expo/', 'href="./_expo/');
fs.writeFileSync(index, html);
for (const name of fs.readdirSync(path.join(__dirname, '../public'))) if(name !== 'topbar.html') fs.copyFileSync(path.join(__dirname, '../public', name), path.join(folder, name));
fs.writeFileSync(path.join(folder, '.nojekyll'), '');
